env: smarts

env_args:
  agent_num: 2
  continuing_episode: False
  scenarios: "./SMARTS/scenarios/straight"
  episode_limit: 50  # 100
  seed: 10
  headless: True

test_greedy: True
test_nepisode: 32
test_interval: 1000
log_interval: 1000
runner_log_interval: 1000
learner_log_interval: 1000
t_max: 20500
