env: smarts

env_args:
  agent_num: 2
  continuing_episode: False
  scenarios: "./SMARTS/scenarios/straight"
  episode_limit: 1000
  seed: 10
  headless: True

test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2050000
